spring:
    application:
        name: module-items-bc
    datasource:
        url: jdbc:postgresql://localhost:5432/FPFL-V2
        username: postgres
        password: xbt20o19A
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                default_schema: FPFL

Server:
    port: 8081
    servlet:
        context-path: /module-items-bc
