spring:
  application:
    name: module-api
  datasource:
    url: jdbc:postgresql://localhost:5432/FPFL-V2
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          default_schema: FPFL

server:
  port: 8000
